<?php
return [
    'welcome' => 'Welcome to Atur Uangmu!',
    'greeting' => 'Hello :name, let\'s manage your finances today.',

    //add to sidebar
    'menu_dashboard' => 'Dashboard',
    'menu_history' => 'History',
    'menu_WA' => 'WhatsApp',

    //add to card transaction
    'card_balance' => 'Current Balance',
    'card_income' => 'Income',
    'card_expense' => 'Expense',

    //button
    'btn_add' => 'Add Transaction',
    'btn_logout' => 'Logout',
    'btn_cancel'=> 'Cancel',

    //transactions
    'latest_transactions' => 'Latest Transactions',
    'view_all' => 'View All',
    'no_transactions'=> 'No transactions today',

    //modal add transactions
    'btn_add_modal'=> 'Add Transaction',
    'btn_income_modal'=> 'Income',
    'btn_expense_modal'=> 'Expense',
    'btn_save_modal' => 'Save Transaction',
    'modal_sub'=>'Keep track of your income and expenses effortlessly.',
    'title_category'=> 'Category',
    'title_desc'=> 'Description',
    'select_category'=>'Select Categories',
    'place_desc'=> 'January salary, cake, and others',
    'label_amount'=> 'Amount',
    'placeholder_amount'=> 'e.g.50.000',

    //categories
    'Salary' => 'Salary',
    'Food & Beverage' => 'Food & Beverage',
    'Transportation' => 'Transportation',
    'Shopping' => 'Shopping',
    'Entertainment' => 'Entertainment',
    'Medical' => 'Medical',
    //Setting
    'settings'=>'Setting',
    'language'=>'Language',
    'currency'=> 'Currency',

    //History
    'history'   =>'History Transaction',
    'title_history'=> 'Tracking all your incoming and outgoing money.',
    

    //Table History
    'Table_history'=> 'History of Transactions',
    'date'=>'Date',
    'description_tbl'=>'Description',
    'tbl_category'=>'Categories',

    //WA Demo
    'menu_WA'=> 'WhatsApp API',
    'wa_title' => 'WhatsApp API Simulator',
    'wa_name'=> 'Customer Name',
    'wa_message'=> 'Auto Message',
    'wa_btn'=> 'TEST SEND NOW',
    'WA_desc'=> 'Enter your order',
    'Wa_name_cust'=> 'e.g. Alex',
    'wa_wa_hello'         => 'Hello, I am',
    'wa_wa_message_label' => 'Message',

    //grafik
    'cash_flow_title' => 'Cash Flow Last 7 Days',
    'income'=>'Income',
    'expense'=>'Expense',

    //budget
    'menu_budgets'=>'Budget',
    'monitoring_title' => 'Budget Monitoring',
    'set_new_budget'   => 'Set New Budget',
    'category_label'   => 'Budget Category',
    'nominal_label'    => 'Amount (Rp)',
    'save_button'      => 'Save Budget',
    'usage_detail'     => 'Usage Details',
    'spent'            => 'Spent',
    'limit'            => 'Limit',
    'safe'             => 'Safe',
    'warning'          => 'Warning',
    'danger'           => 'Danger',
    'budgets_placeholder'=>'e.g.50000',
    'empty_data' => 'No data',
    'btn_edit_budgets'=> 'Change budget',
    'expense_by_category'=> 'Expenses by category',

    //report
    'menu_report'=>'Report',
    'title_report'=> 'Generate Report',
    'lable_report' => 'Report',
    'otomated' => 'Automated Financial Generator',
    'label_btnexp'=> 'Export as Professional PDF',
    'Mperiode'=>'Start Periode',
    'Nperiode'=>'End Periode',
    'btnR'=> 'Generate Report',
    'transaction'=> 'Recent transactions',
    'title_tab'=> 'Recent 3',
    'title_no_data' => 'No Data in This Period',

    //System Guide
    'Lable_guide' => 'System Guide',
    'title_guide' => 'Maximize your financial insight.',
    'title01_guide' => 'Use monthly filters for more accurate reports',
    'title02_guide' => 'Report data is local and encrypted to protect your financial privacy.',

    // Web UI / Sidebar
    'start_date'    => 'Start Date',
    'end_date'      => 'End Date',
    'generate'      => 'Download Report Now',
    'recent_trx'    => 'Recent Transactions History',
    'no_data'       => 'No data found for this period',
    'confirm_delete'=> 'Confirm you want to delete this data?',

    // Financial PDF Report
    'pdf_title'     => 'Monthly Financial Statement',
    'generated_on'  => 'Generated on',
    'period'        => 'Period',
    'total_income'  => 'Total Income',
    'total_expense' => 'Total Expense',
    'net_balance'   => 'Net Balance',
    'date'          => 'Date',
    'description'   => 'Description',
    'category'      => 'Category',
    'amount'        => 'Amount',
    'footer_note'   => 'This report is automatically generated by AturUangmu System. Data is confidential and accurate based on user input.',
];
